### ISSUE TITLE
The installation in your README.md is missleading

### ISSUE THREAD

**Issue by stela2502** [caleblareau/maegatk#10]
Hi and thank you for that tool.
Having installed it I wonder why you hide the fact that this program also needs picard (which is missing even in your wiki page), bwa, bedtools,  freebayes and even R with 4 packages?

This information would definitely also be nice in the README.md.

**Comment by noranekonobokkusu** [comment]
Hi,

thank you for your feedback, the README.md have been largely restructured and expanded, so all the dependencies are now listed there. Picard is provided as a .jar file in the bin/ folder.

**Comment by stela2502** [comment]
Great! Thank you.
