### ISSUE TITLE
Merge query

### ISSUE THREAD

**Issue by cdeaton380** [caleblareau/maegatk#19]
Hi!

I have a questions regarding pre-processing before maegatk. Before merging, should we be subsetting both MAESTER and scRNA-seq files for chrM? Or do we merge scRNA-seq .bam files containing data from all chromosomes with subsetted MAESTER? 
I've been running the supplied test files with maegatk and found that there are only reads aligned to chrM in this file.

Any help you can provide will be super useful!
Thanks!

**Comment by petervangalen** [comment]
I usually subset the bam file after alignment with STAR and before running maegatk as follows:
`samtools view $INPUT MT -b > $OUTPUT`
I don't think the mitochondrial alignments from the scRNA-seq sequencing will add a lot of value, but if you want to add them, you could use `samtools merge` and `samtools sort`
