### ISSUE TITLE
Description about the output files and contents

### ISSUE THREAD

**Issue by hisplan** [caleblareau/maegatk#2]
Hi,

Is there any doc that describes about the files generated by `maegatk bcall`, especially those files under the `final` directory, and what each column means in each file?

Thanks!

**Comment by caleblareau** [comment]
Apologies for the slow response-- we are working on refurbinshing the documentation. 

see here for the code that produces the files: https://github.com/caleblareau/maegatk/blob/master/maegatk/bin/python/sumstatsBP.py#L125

Basically, the order is `count_fw, mean_base_qual_fw, count_rev, mean_base_qual_rev` per position per cell (noting that this is within the `A/C/G/T` file.
