### ISSUE TITLE
Tutorial normal workflow for 10x data

### ISSUE THREAD

**Issue by balthasar0810** [caleblareau/maegatk#9]
Hello,

is there a tutorial describing a normal workflow for clonal analysis from 10x data (after mitochondrial read amplification following Miller et al. NatBiotech)?

Thanks, Chris

**Comment by petervangalen** [comment]
Hi Chris,
Not a tutorial, but I tried to share the code understandably: https://github.com/petervangalen/MAESTER-2021
Peter

**Comment by balthasar0810** [comment]
Oh thanks, btw, it’s me, Peter, Christian Hinze who contacted you about single nuc a while ago.

We will try to use your protocol on human single NUC cDNA next week. We are curious to see what this brings. Some colleagues were not very optimistic as we have an average 0.6% perc.mito in our data. But we want to give it a try as I understood from our previous interaction that it is not strictly impossible (?).

Janna will be in touch with the colleague from your lab you put us in contact with about some remaining details.

Also thanks for the updated primer list! Chris

Envoyé de mon iPhone

Le 20.11.2022 à 13:40, Peter van Galen ***@***.***> a écrit :

﻿

Hi Chris,
Not a tutorial, but I tried to share the code understandably: https://github.com/petervangalen/MAESTER-2021
Peter

**Comment by petervangalen** [comment]
Hi Chris, you are welcome to try. 0.6% is about ten times lower than what I'm used to from 10x 3' scRNA-seq libraries. You may be able to discern homoplasmic variants between cells from different individuals, but I expect _de novo_ identification of informative variants for the purpose of intra-individual clonal inference to be extremely challenging or impossible. Good luck.
